---
name: Run Prime UI Checks
description: "Runs Prime UI checks"

inputs:
  reporting:
    description: "Enable reporting"
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Run Prime UI Checks
      run: |
        set +e
        gotestsum --format standard-verbose --packages=github.com/rancher/tests/validation/prime \
        --junitfile results.xml --jsonfile results.json -- -timeout=3h -tags=prime -v;
        exit_code=$?;
        echo "exit_code=$exit_code" >> $GITHUB_ENV;
        if [[ "${{ inputs.reporting }}" == "true" ]]; then
          ./validation/pipeline/scripts/build_qase_reporter_v2.sh;
          ./validation/reporter
        fi
      shell: bash

    - name: Show failed tests
      run: |
        failed=0
        if [ "$exit_code" -ne 0 ]; then
          echo "Failed tests:"
          jq -r 'select(.Action=="fail" and .Test != null) | "- " + .Test' results.json
          failed=1
        fi

        if [ "$failed" -eq 1 ]; then
          exit 1
        fi
      shell: bash