#!groovy

node("vsphere-vpn-1") {
  def job_name = "${JOB_NAME}"
  if (job_name.contains('/')) {
    job_names = job_name.split('/')
    job_name = job_names[job_names.size() - 1]
  }
  def testContainer = "${job_name}${env.BUILD_NUMBER}_test"
  def imageName = "qa-custodian-${job_name}${env.BUILD_NUMBER}"
  def testResultsOut = "results.xml"
  def envFile = ".env"
  def rancherConfig = "rancher_env.config"
  def awsYaml = "aws.yaml"
  def azureYaml = "azure.yaml"
  def gcpYaml = "gcp.yaml"
  def linodeScript = "linode.sh"
  def awsMonthly = "aws-monthly.yaml"
  if ("${env.CUSTODIAN_YAML}" != "null" && "${env.CUSTODIAN_YAML}" != "") {
    yamlToRun = "${env.CUSTODIAN_YAML}"
  }
  def branch = "main"
  if ("${env.branch}" != "null" && "${env.branch}" != "") {
    branch = "${env.branch}"
  }
  def repo = scm.userRemoteConfigs
  if ("${env.REPO}" != "null" && "${env.REPO}" != "") {
    repo = [
      [url: "${env.REPO}"]
    ]
  }
  withFolderProperties {
    paramsMap = []
    params.each {
      if (it.value && it.value.trim() != "") {
        paramsMap << "$it.key=$it.value"
      }
    }
    withEnv(paramsMap) {
      withCredentials([string(credentialsId: 'AWS_ACCESS_KEY_ID', variable: 'AWS_ACCESS_KEY_ID'),
        string(credentialsId: 'AWS_SECRET_ACCESS_KEY', variable: 'AWS_SECRET_ACCESS_KEY'),

        string(credentialsId: 'QA_IAM_WEBHOOK', variable: 'QA_IAM_WEBHOOK'),
        string(credentialsId: 'SQS_URL', variable: 'SQS_URL'),
        string(credentialsId: 'ARN_ROLE', variable: 'ARN_ROLE'),

        string(credentialsId: 'DONOTDELETE_KEYS', variable: 'DONOTDELETE_KEYS'),
        string(credentialsId: 'USER_KEYS', variable: 'USER_KEYS'),

        string(credentialsId: 'AZURE_AKS_SUBSCRIPTION_ID', variable: 'AZURE_AKS_SUBSCRIPTION_ID'),
        string(credentialsId: 'AZURE_TENANT_ID', variable: 'AZURE_TENANT_ID'),
        string(credentialsId: 'AZURE_CLIENT_ID', variable: 'AZURE_CLIENT_ID'),
        string(credentialsId: 'AZURE_CLIENT_SECRET', variable: 'AZURE_CLIENT_SECRET'),
        string(credentialsId: 'GOOGLE_CLOUD_PROJECT', variable: 'GOOGLE_CLOUD_PROJECT'),

        string(credentialsId: 'RANCHER_GKE_CREDENTIAL', variable: 'RANCHER_GKE_CREDENTIAL'),

        string(credentialsId: 'RANCHER_LINODE_ACCESSKEY', variable: "RANCHER_LINODE_ACCESSKEY")
      ]) {
        stage('Checkout') {
          deleteDir()
          checkout([
            $class: 'GitSCM',
            branches: [
              [name: "*/${branch}"]
            ],
            extensions: scm.extensions + [
              [$class: 'CleanCheckout']
            ],
            userRemoteConfigs: repo
          ])
        }
        dir("./scripts/custodian/") {
          try {
            stage('Build Docker Image') {
              try {
                def decoded = new String(RANCHER_GKE_CREDENTIAL.decodeBase64())
                writeFile file: 'google_credentials.json', text: decoded
                sh returnStdout: true, script: 'wget -qO ./jq https://github.com/jqlang/jq/releases/latest/download/jq-linux-amd64'
                sh returnStdout:true, script: 'chmod a+x ./jq'
                sh """
docker build -t ${imageName} -f Dockerfile . \
  --build-arg AWS_ACCESS_KEY_ID='${AWS_ACCESS_KEY_ID}' \
  --build-arg AWS_SECRET_ACCESS_KEY='${AWS_SECRET_ACCESS_KEY}' \
  --build-arg AZURE_AKS_SUBSCRIPTION_ID='${AZURE_AKS_SUBSCRIPTION_ID}' \
  --build-arg AZURE_TENANT_ID='${AZURE_TENANT_ID}' \
  --build-arg AZURE_CLIENT_ID='${AZURE_CLIENT_ID}' \
  --build-arg AZURE_CLIENT_SECRET='${AZURE_CLIENT_SECRET}' \
  --build-arg RANCHER_LINODE_ACCESSKEY='${RANCHER_LINODE_ACCESSKEY}' \
  --build-arg GOOGLE_CLOUD_PROJECT='${GOOGLE_CLOUD_PROJECT}' \
  --build-arg QA_IAM_WEBHOOK='${QA_IAM_WEBHOOK}' \
  --build-arg SQS_URL='${SQS_URL}' \
  --build-arg ARN_ROLE='${ARN_ROLE}'
"""
              } catch (err) {
                echo 'Docker Build had partial failures...'
                echo "${err}"
              }
            }
            stage('Run Docker Image for Adding Tags') {
              // if a user only wants to run the test using a subset of keys, they can pass in OVERRIDE_REGION
              if ("${env.OVERRIDE_REGION}" != "null" && "${env.OVERRIDE_REGION}" != "") {
                sh "docker run --privileged --name ${testContainer} -e CUSTODIAN_YAML=\"tag-to-save.yaml\" -e OVERRIDE_REGION=\"${env.OVERRIDE_REGION}\" -e DONOTDELETE_KEYS=\"${DONOTDELETE_KEYS}\" -e QA_IAM_WEBHOOK=\"${QA_IAM_WEBHOOK}\" -e USER_KEYS=\"${TAG_USER_KEYS}\" ${imageName} "
              }
            }

            stage('Run Docker Image for AWS, Azure, GCP, and Linode') {
              if ("${CUSTODIAN_YAML}" != "${linodeScript}" && "${CUSTODIAN_YAML}" != "${awsMonthly}") {
                sh "docker run --privileged --name ${testContainer} -e CUSTODIAN_YAML=\"${CUSTODIAN_YAML}\" -e DONOTDELETE_KEYS=\"${DONOTDELETE_KEYS}\" -e QA_IAM_WEBHOOK=\"${QA_IAM_WEBHOOK}\" -e USER_KEYS=\"${USER_KEYS}\" ${imageName}"
              } else if ("${CUSTODIAN_YAML}" == "${awsMonthly}") {
                sh "docker run --privileged --name ${testContainer} -e CUSTODIAN_YAML=\"${awsMonthly}\" -e OVERRIDE_REGION=\"us-east-2\" -e DONOTDELETE_KEYS=\"${DONOTDELETE_KEYS}\" -e QA_IAM_WEBHOOK=\"${QA_IAM_WEBHOOK}\" -e USER_KEYS=\"${USER_KEYS}\" ${imageName} "
              } else {
                sh ". ${linodeScript}"
              }
            }
          } catch (err) {
            echo "error during custodian run"
            echo "${err}"
          }

          sh "docker stop ${testContainer}"
          sh "docker rm -v ${testContainer}"
          sh "docker rmi -f ${imageName}"
        } // dir 
      } // creds
    } // folder properties
  }
} // node