FROM registry.suse.com/bci/golang:1.24

# Configure Go
ENV GOPATH=/root/go
ENV PATH=${PATH}:/root/go/bin

ENV WORKSPACE=${GOPATH}/src/github.com/rancher/tests

WORKDIR $WORKSPACE/validation

COPY [".", "$WORKSPACE"]

RUN go mod download && \
    go install gotest.tools/gotestsum@latest

RUN mkdir /root/.ssh && chmod 600 .ssh/jenkins-*
RUN zypper install -y openssh
RUN for pem_file in .ssh/jenkins-*; do \
      ssh-keygen -f "$pem_file" -y > "/root/.ssh/$(basename "$pem_file").pub"; \
    done

RUN CGO_ENABLED=0

# necessary to run if statements using [[ ]]
SHELL ["/bin/bash", "-c"] 


ARG RKE_VERSION
RUN if [[ -n "$RKE_VERSION" ]] ; then echo installing latest version RKE && \
    curl -0Ls https://github.com/rancher/rke/releases/latest/download/rke_linux-amd64 > rke ; else echo installing ${RKE_VERSION} version RKE && \
    curl -0Ls https://github.com/rancher/rke/releases/download/$RKE_VERSION/rke_linux-amd64 > rke; fi;
RUN mv rke /bin/rke && \
    chmod +x /bin/rke


ARG CLI_VERSION
RUN if [[ -n "$CLI_VERSION" ]] ; then  \
        echo installing CLI version $CLI_VERSION ; \
        curl -LO https://github.com/rancher/cli/releases/download/$CLI_VERSION/rancher-linux-amd64-$CLI_VERSION.tar.gz ; \
        tar -xf rancher-linux-amd64-$CLI_VERSION.tar.gz && \
        mv rancher-$CLI_VERSION/rancher /bin/rancher && \
        chmod +x /bin/rancher; fi;