name: Qase Test Upload
on:
  push:
    branches:
      - 'main'
    paths:
      - '**/schemas/**'
  
jobs:
  run-script:
    name: update-qase
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
      
      - name: Setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "./go.mod"
          cache-dependency-path: "**/*.sum"

      - name: Update Qase Tests
        env:
          QASE_AUTOMATION_TOKEN: ${{ secrets.QASE_AUTOMATION_TOKEN }}
        run: go run ./validation/pipeline/qase/schemaupload/main.go